### ISSUE TITLE
ddnsto不能使用问题

### ISSUE THREAD

**Issue by TomYule** [updateing/lede-source#4]
ddnsto不能使用问题

**Comment by updateing** [comment]
本仓库并不包含 ddnsto 这个包，请去相关仓库提交问题。

**Comment by TomYule** [comment]
> 本仓库并不包含 ddnsto 这个包，请去相关仓库提交问题。

不是吧 就是刷的这个固件

**Comment by updateing** [comment]
> 不是吧 就是刷的这个固件

请给出固件来源。
