### ISSUE TITLE
Problem about enabling XHCI support

### ISSUE THREAD

**Issue by ghost** [updateing/lede-source#5]
Hello, thanks for your job. This is a magnificent project! I tested your .trz on my K3 device, everything seems OK. 

However, when I build it in my own way, usb 3.0 does not function at all. There is even no any `xhci` presented in dmesg logs at all. Of course, I selected all common necessary usb module by `make menuconfig`, including `kmod-brcmfmac`, `kmod-phy-bcm-ns-usb2(3)`, `kmod-usb2(3)`, `usb-storage(-uas)`, `kmod-ext4(ntfs, vfat)` and so on.

My question is, how did you achieve functioning **xhci**, like [this](http://koolshare.cn/forum.php?mod=redirect&goto=findpost&ptid=92162&pid=947231)? I also noticed that **northstar driver** seemed relevent to that, as [this post](http://koolshare.cn/forum.php?mod=redirect&goto=findpost&ptid=91998&pid=1129104) showing. Is there any further deep job I have to complete in order to perfect its work?

**Comment by updateing** [comment]
Could you please upload full boot log? The code in this repo is too old and might not work with latest upstream changes.

**Comment by ghost** [comment]
I have rewritten the code and thus solved the XHCI issue.

**Comment by ghost** [comment]
Based on your previous job, I've adapted it to fit the current kernel. It's been [merged](https://github.com/openwrt/openwrt/commit/62dadcb86c6e6f80ce6fbcd89befc3cc22c2176a) to OpenWrt officially. Thank you!
Hope the [LCD package](https://github.com/updateing/k3screenctrl) could be done completely. Currently, it's not fully supported on my K3-D1.
